name: JoinLeaveMessage
version: ${project.version}
main: me.skygamezmc.joinleavemessage.JoinLeaveMessage
api-version: 1.16
authors: [skygamezMC]
description: A lite join/leave message!

depend: [PlaceholderAPI]
commands:
  jlm: