name: JoinLeaveMessage
version: ${project.version}
main: me.skygamezmc.joinleavemessage.JoinLeaveMessage
api-version: 1.13
authors: [skygamezMC]
description: A lite join/leave message!

softdepend: [PlaceholderAPI]
commands:
  jlm:
